### ISSUE TITLE
Can Shared Storage be used from Fenced Frames during Origin Trials?

### ISSUE THREAD

**Issue by gota0** [WICG/fenced-frame#102]
Currently, I am getting an error `The "shared-storage" Permissions Policy denied the method on window.sharedStorage` when a Shared Storage value is about to be set from within a Fenced Frame.
The documentation, [Permission policy for API backed fenced frames](https://github.com/WICG/fenced-frame/blob/master/explainer/permissions_policy_for_API_backed_fenced_frames.md#introduction) 
states, 

> the OT recently added an exception for attribution-reporting and shared-storage APIs. It allows a fenced frame to be navigated successfully only if the embedding frame has not opted out from these features and enables it for the fenced frame by default (without an allow attribute).

My understanding is that although permission policies are disabled for Fenced Frames during the Origin Trials, it is supposed to allow Shared Storage usage from within a Fenced Frame by default. 
Is my understanding that Shared Storage values can be set currently from within a Fenced Frame incorrect? Or should I check if I have explicitly opted out from shared-storage usage?

**Comment by shivanigithub** [comment]
Thanks for raising the question!
There were some Chrome versions for which sharedStorage APIs were disallowed in fenced frames and now it's enabled back in M115.
If you run your code in M115 canary/dev/beta channels, it should succeed. Let us know if you still run into issues.

**Comment by gota0** [comment]
Updating to M116 Chrome Canary solved the issue. Thank you!
