### ISSUE TITLE
[Spec] How fenced frames behaves with embedder policy?

### ISSUE THREAD

**Issue by yoshisatoyanagisawa** [WICG/fenced-frame#11]
Fenced frames will be treated as top-level browsing contexts, and [the existing spec](https://html.spec.whatwg.org/multipage/origin.html#check-a-navigation-response's-adherence-to-its-embedder-policy) says "If target is not a child browsing context, then return true."  Therefore, no embedder policy would be applied if we literary understand the spec.

We might need to update the spec to tell how the policy should be applied for fenced frames.

**Comment by domfarolino** [comment]
This is done with the changes made in https://wicg.github.io/fenced-frame/#coop-coep, per https://github.com/WICG/fenced-frame/pull/69.
