### ISSUE TITLE
[Spec] Default sandbox flags for fenced frames

### ISSUE THREAD

**Issue by shivanigithub** [WICG/fenced-frame#12]
Detailed document related to this is [here](https://docs.google.com/document/d/1RO4NkQk_XaEE7vuysM9LJilZYsoOhydfh93sOvrPQxU/edit?usp=sharing)

**Comment by domfarolino** [comment]
We no longer have "default" sandbox flags in fenced frames since the "config" redesign. Given this, and the fact that the task of integrating with sandbox flags is tracked in our public spec tracker doc, I'll close this.
