### ISSUE TITLE
Spec the interface that provides fenced-frame-only APIs

### ISSUE THREAD

**Issue by domfarolino** [WICG/fenced-frame#14]
We are currently thinking this would exist on `Window` and be called `fencedAPIs`. Similar to `frameElement` it would be null based on runtime logic.

**Comment by shivanigithub** [comment]
Two of the APIs here would be:
- Navigate the top-level page
- reportEvent which is defined in https://github.com/WICG/turtledove/blob/main/Fenced_Frames_Ads_Reporting.md

**Comment by domfarolino** [comment]
`window.fence` has been specified at this point via https://wicg.github.io/fenced-frame/#fence-interface, so I'll close this.
