### ISSUE TITLE
Allow-Cross-Origin-Event-Reporting not defined?

### ISSUE THREAD

**Issue by miketaylr** [WICG/fenced-frame#158]
Looking at https://github.com/WICG/fenced-frame/pull/152 - I see `Allow-Cross-Origin-Event-Reporting` referenced, but not defined. I can see that it's parsed as a structured field Item, but doesn't say if it's allowed values are string literals `true`/`false` or boolean`?0`/`?1`.

https://httpwg.org/specs/rfc8941.html#rfc.section.2 is a useful guide to reference.

**Comment by domfarolino** [comment]
@blu25
