### ISSUE TITLE
[Spec] Spec _unfencedTop

### ISSUE THREAD

**Issue by gtanzer** [WICG/fenced-frame#166]
This issue blocks https://github.com/WICG/fenced-frame/issues/165

**Comment by domfarolino** [comment]
Just FYI it is unlikely I will get to this. I would recommend assigning to someone more actively working on the project.

**Comment by VergeA** [comment]
FYI I'll be taking this work up going forward.

**Comment by domfarolino** [comment]
#200 Closed this.
