### ISSUE TITLE
Meetings: Organizing WICG calls for Fenced Frames

### ISSUE THREAD

**Issue by shivanigithub** [WICG/fenced-frame#33]
We will organize WICG meetings to discuss Fenced Frames related topics as we accumulate topics.

Please enter agenda items as comments/suggestions in [this Google Doc](https://docs.google.com/document/d/1EMCnLODUsjBBj9ObPU5nYoQlYDgGbEgiJ59SWMPLRpo/edit?usp=sharing).

Please comment/watch/star this issue to make suggestions, or receive notifications regarding meetings.

**Comment by domfarolino** [comment]
From chatting offline, we think it's OK to close this issue now.
