### ISSUE TITLE
[Spec] Define behavior for focus gating

### ISSUE THREAD

**Issue by blu25** [WICG/fenced-frame#36]
Focus for a fenced frame is gated on user activation to prevent a script from pulling focus across a fenced boundary. This behavior should be formalized in the spec.

Design doc: https://docs.google.com/document/d/18W-lq8uexg-vFfq0cxM6IGshwaAInjpdit-jAhhOytI/edit?usp=sharing

**Comment by domfarolino** [comment]
Done in https://github.com/WICG/fenced-frame/pull/68 & https://wicg.github.io/fenced-frame/#focusing-changes.
