### ISSUE TITLE
Detecting Ad Blockers

### ISSUE THREAD

**Issue by RussStringham** [WICG/fenced-frame#4]
If the publisher cannot interact with the fence frame, how can the publisher verify that ads are actually being displayed? If they are getting no revenue from this user, they may want to put up a dialog asking the user to either turn off their ad blocker or pay for content before allowing them to see it.

**Comment by shivanigithub** [comment]
Thanks for the question!

Note that contextual ads will still be displayed in iframes. Only specific use cases like interest based ads will be rendered in fenced frames. So publisher can get the presence of ad-blocker information from determining whether a contextual ad got rendered or not. Does that answer the concern?

**Comment by domfarolino** [comment]
Closing this as we haven't heard back for about 2 years and there doesn't seem to be action we can take on this. Please feel free to comment or re-open if you'd like to continue the discussion.
