### ISSUE TITLE
What is the behavior of reportEvent in iFrame?

### ISSUE THREAD

**Issue by shaojieg** [WICG/fenced-frame#58]
Hi, 

reportEvent is designed for Fenced Frame. What is the function's behavior when the JS script is loaded in iFrame? Is it a no-op?

Thanks,
Shaojie

**Comment by domfarolino** [comment]
Can you clarify what you mean by "when the JS script is loaded in iFrame"?

**Comment by shivanigithub** [comment]
@shaojieg reached out offline and we discussed that this is a FLEDGE urn-iframe, in which case reportEvent is supported.
(In a regular iframe, reportEvent is not supported.)
 I believe we can close this issue here.
