### ISSUE TITLE
Permissions policy allow attribute?

### ISSUE THREAD

**Issue by amtunlimited** [WICG/fenced-frame#6]
Will there be a permissions policy allow attribute, like a regular frame? I personally think there should be, but it could lead to some interesting artifacts (like how the permissions policy from the header wouldn't match the policies visible to the JS context)

Also of interest for Client Hints.

**Comment by amtunlimited** [comment]
Gentle ping, any thoughts?

**Comment by shivanigithub** [comment]
Thanks for the ping! 
The initial thoughts on this is that having an 'allow' attribute would lead to a channel between the embedding frame and the fenced frame.
Having said that, we are thinking about permission policy as well as the behavior with document policy and CSPEE a bit more in detail at the moment and will get back with more updates.

**Comment by amtunlimited** [comment]
I forgot to write this down, but we had a chat off-band and the discussion ended up at giving the frame the ability to request client hints as though it were a top level frame (meaning no permission-policy control from frames above), but not being able to store them.

**Comment by shivanigithub** [comment]
For completeness, this [doc](https://docs.google.com/document/d/16PNR2hvO2oo93Mh5pGoHuXbvcwicNE3ieJVoejrjW_w/edit?usp=sharing) goes into the details.

**Comment by domfarolino** [comment]
We've added the `allow` attribute the fenced frame element, and it is spec'd in https://wicg.github.io/fenced-frame/#element-attrdef-fencedframe-allow, and the permissions policy integration spec is in https://wicg.github.io/fenced-frame/#permissions-policy-changes so I think this can be closed now.
