### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by JensenPaul** [WICG/fenced-frame#60]
"[Modes/Use cases of fenced frames](https://github.com/shivanigithub/fenced-frame/blob/master/explainer/modes.md)" link on https://github.com/WICG/fenced-frame is broken

**Comment by shivanigithub** [comment]
@gtanzer Can you please add the new relevant link since modes.md was replaced in your config PR. Thanks!

**Comment by gtanzer** [comment]
https://github.com/WICG/fenced-frame/pull/61
