### ISSUE TITLE
Explainer: mention the developer-only flag to enable `FencedFrameConfig` constructor

### ISSUE THREAD

**Issue by domfarolino** [WICG/fenced-frame#94]
In Chromium, we're implementing a flag in `chrome://flags` to enable what we're calling "default mode", which exposes the [`FencedFrameConfig`](https://wicg.github.io/fenced-frame/#fencedframeconfig) constructor so you can more-easily use fenced frames without setting up the whole auction ceremony and infrastructure.

We should mention this in the explainer for ease of developer testing and adoption.

/cc @shivanigithub

**Comment by shivanigithub** [comment]
Might make sense to move this to be a devTools flag

**Comment by blu25** [comment]
Closing this out since the explainer update was merged in https://github.com/WICG/fenced-frame/pull/110
